name: Tests and formatting

on:
    push:
    merge_group:

jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Format check
              run: npm run lint && echo 'No lint issues!' || (npm run lint-fix; git diff; echo 'Lint check failed, review diff above or run "npm run lint.fix"'; return 1)
